/*type ChangeTypeToChannelAndState<Obj> = Obj extends object
    ? {
          [K in keyof Obj]-?: ChangeTypeToChannelAndState<Obj[K]>;
      } & customChannelType
    : ioBroker.StateObject;
export type ChangeToChannel<Obj, T> = Obj extends object
    ? { [K in keyof Obj]-?: customChannelType & T }
    : ioBroker.StateObject;
*/
export type ChangeTypeOfKeysForState<Obj, N> = Obj extends object
    ? customChannelType & { [K in keyof Obj]: ChangeTypeOfKeysForState<Obj[K], N> }
    : N;
export type customChannelType = {
    _channel?: ioBroker.ChannelObject | ioBroker.DeviceObject | ioBroker.FolderObject;
    _array?: ioBroker.ChannelObject | ioBroker.DeviceObject | ioBroker.FolderObject;
};

const TemperatureData: ChangeTypeOfKeysForState<TemperatureData, ioBroker.StateObject> = {
    temperature: {
        _id: '',
        type: 'state',
        common: {
            name: 'Temperature',
            type: 'number',
            role: 'value.temperature',
            read: true,
            write: false,
            unit: '°C',
        },
        native: {},
    },
    apparentTemperature: {
        _id: '',
        type: 'state',
        common: {
            name: 'Apparent Temperature',
            type: 'number',
            role: 'value.temperature',
            read: true,
            write: false,
            unit: '°C',
        },
        native: {},
    },
    dewPoint: {
        _id: '',
        type: 'state',
        common: {
            name: 'Dew Point',
            type: 'number',
            role: 'value.temperature',
            read: true,
            write: false,
            unit: '°C',
        },
        native: {},
    },
    humidity: {
        _id: '',
        type: 'state',
        common: {
            name: 'Humidity',
            type: 'number',
            role: 'value.humidity',
            read: true,
            write: false,
            unit: '%',
        },
        native: {},
    },
};
const WindData: ChangeTypeOfKeysForState<WindData, ioBroker.StateObject> = {
    windSpeed: {
        _id: '',
        type: 'state',
        common: {
            name: 'Wind Speed',
            type: 'number',
            role: 'value.speed.wind',
            read: true,
            write: false,
            unit: 'm/s',
        },
        native: {},
    },
    windGust: {
        _id: '',
        type: 'state',
        common: {
            name: 'Wind Gust',
            type: 'number',
            role: 'value.speed.wind.gust',
            read: true,
            write: false,
            unit: 'm/s',
        },
        native: {},
    },
    windBearing: {
        _id: '',
        type: 'state',
        common: {
            name: 'Wind Bearing',
            type: 'number',
            role: 'value.direction.wind',
            read: true,
            write: false,
            unit: '°',
        },
        native: {},
    },
    windBearingText: {
        _id: '',
        type: 'state',
        common: {
            name: 'Wind Bearing Text',
            type: 'string',
            role: 'weather.direction.wind',
            read: true,
            write: false,
        },
        native: {},
    },
};
const PressureVisibilityOzoneData: ChangeTypeOfKeysForState<PressureVisibilityOzoneData, ioBroker.StateObject> = {
    pressure: {
        _id: '',
        type: 'state',
        common: {
            name: 'Pressure',
            type: 'number',
            role: 'value.pressure',
            read: true,
            write: false,
            unit: 'hPa',
        },
        native: {},
    },
    visibility: {
        _id: '',
        type: 'state',
        common: {
            name: 'Visibility',
            type: 'number',
            role: 'value.distance.visibility',
            read: true,
            write: false,
            unit: 'km',
        },
        native: {},
    },
    ozone: {
        _id: '',
        type: 'state',
        common: {
            name: 'Ozone',
            type: 'number',
            role: 'value',
            read: true,
            write: false,
            unit: 'DU',
        },
        native: {},
    },
};
const CloudUvData: ChangeTypeOfKeysForState<CloudUvData, ioBroker.StateObject> = {
    cloudCover: {
        _id: '',
        type: 'state',
        common: {
            name: 'Cloud Cover',
            type: 'number',
            role: 'value.clouds',
            read: true,
            write: false,
            unit: '%',
        },
        native: {},
    },
    uvIndex: {
        _id: '',
        type: 'state',
        common: {
            name: 'UV Index',
            type: 'number',
            role: 'value.uv',
            read: true,
            write: false,
        },
        native: {},
    },
};

const MetaData: ChangeTypeOfKeysForState<MetaData, ioBroker.StateObject> = {
    summary: {
        _id: '',
        type: 'state',
        common: {
            name: 'Summary',
            type: 'string',
            role: 'weather.title',
            read: true,
            write: false,
        },
        native: {},
    },
    icon: {
        _id: '',
        type: 'state',
        common: {
            name: 'Icon',
            type: 'string',
            role: 'weather.icon.name',
            read: true,
            write: false,
        },
        native: {},
    },
};
const PrecipitationData: ChangeTypeOfKeysForState<PrecipitationData, ioBroker.StateObject> = {
    precipIntensity: {
        _id: '',
        type: 'state',
        common: {
            name: 'Precipitation Intensity',
            type: 'number',
            role: 'value.precipitation',
            read: true,
            write: false,
            unit: 'mm',
        },
        native: {},
    },
    precipProbability: {
        _id: '',
        type: 'state',
        common: {
            name: 'Precipitation Probability',
            type: 'number',
            role: 'value',
            read: true,
            write: false,
            unit: '%',
        },
        native: {},
    },
    precipIntensityError: {
        _id: '',
        type: 'state',
        common: {
            name: 'Precipitation Intensity Error',
            type: 'number',
            role: 'value',
            read: true,
            write: false,
            unit: 'mm',
        },
        native: {},
    },
    precipAccumulation: {
        _id: '',
        type: 'state',
        common: {
            name: 'Precipitation Accumulation',
            type: 'number',
            role: 'value',
            read: true,
            write: false,
            unit: 'cm',
        },
        native: {},
    },
    precipType: {
        _id: '',
        type: 'state',
        common: {
            name: 'Precipitation Type',
            type: 'string',
            role: 'text',
            read: true,
            write: false,
        },
        native: {},
    },
};

export const defaultChannel: ioBroker.ChannelObject = {
    _id: '',
    type: 'channel',
    common: {
        name: 'Hey no description... ',
    },
    native: {},
};

export const genericStateObjects: {
    default: ioBroker.StateObject;
    customString: ioBroker.StateObject;
    weather: customChannelType & {
        hourly: customChannelType &
            ChangeTypeOfKeysForState<MetaData, ioBroker.StateObject> &
            ChangeTypeOfKeysForState<HourlyData, ioBroker.StateObject>;
        daily: customChannelType &
            ChangeTypeOfKeysForState<MetaData, ioBroker.StateObject> &
            ChangeTypeOfKeysForState<DailyData, ioBroker.StateObject>;
        minutely: customChannelType &
            ChangeTypeOfKeysForState<MetaData, ioBroker.StateObject> &
            ChangeTypeOfKeysForState<MinutelyData, ioBroker.StateObject>;
        currently: customChannelType & ChangeTypeOfKeysForState<CurrentlyData, ioBroker.StateObject>;
        latitude: ioBroker.StateObject;
        lastUpdate: ioBroker.StateObject;
        longitude: ioBroker.StateObject;
        timezone: ioBroker.StateObject;
        offset: ioBroker.StateObject;
        elevation: ioBroker.StateObject;
        'nearest-station'?: ioBroker.StateObject;
        version: ioBroker.StateObject;
        units: ioBroker.StateObject;
    };
} = {
    default: {
        _id: 'No_definition',
        type: 'state',
        common: {
            name: 'StateObjects.state',
            type: 'string',
            role: 'text',
            read: true,
            write: false,
        },
        native: {},
    },

    customString: {
        _id: 'User_State',
        type: 'state',
        common: {
            name: 'StateObjects.customString',
            type: 'string',
            role: 'text',
            read: true,
            write: false,
        },
        native: {},
    },
    weather: {
        _channel: {
            _id: '',
            type: 'folder',
            common: {
                name: 'Weather',
            },
            native: {},
        },
        hourly: {
            ...PrecipitationData,
            ...MetaData,
            ...WindData,
            ...TemperatureData,
            ...PressureVisibilityOzoneData,
            ...CloudUvData,
            _channel: {
                _id: '',
                type: 'folder',
                common: {
                    name: 'Hourly',
                },
                native: {},
            },
            _array: {
                _id: '',
                type: 'folder',
                common: {
                    name: 'Hourly',
                },
                native: {},
            },
            time: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Date in Milliseconds',
                    type: 'number',
                    role: 'date',
                    read: true,
                    write: false,
                },
                native: {},
            },
        },
        daily: {
            ...WindData,
            ...MetaData,
            _channel: {
                _id: '',
                type: 'folder',
                common: {
                    name: 'Daily',
                },
                native: {},
            },
            _array: {
                _id: '',
                type: 'folder',
                common: {
                    name: 'Daily',
                },
                native: {},
            },
            time: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Date in Milliseconds',
                    type: 'number',
                    role: 'date',
                    read: true,
                    write: false,
                },
                native: {},
            },
            sunriseTime: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Sunrise Time in Milliseconds',
                    type: 'number',
                    role: 'date.sunrise',
                    read: true,
                    write: false,
                },
                native: {},
            },
            sunsetTime: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Sunset Time in Milliseconds',
                    type: 'number',
                    role: 'date.sunset',
                    read: true,
                    write: false,
                },
                native: {},
            },
            moonPhase: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Moon Phase',
                    type: 'number',
                    role: 'value',
                    read: true,
                    write: false,
                    unit: '%',
                },
                native: {},
            },
            precipIntensity: PrecipitationData.precipIntensity,
            precipIntensityMax: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Maximum Precipitation Intensity',
                    type: 'number',
                    role: 'value',
                    read: true,
                    write: false,
                    unit: 'mm',
                },
                native: {},
            },
            precipIntensityMaxTime: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Maximum Precipitation Intensity Time in Milliseconds',
                    type: 'number',
                    role: 'date',
                    read: true,
                    write: false,
                },
                native: {},
            },
            precipProbability: PrecipitationData.precipProbability,
            precipAccumulation: PrecipitationData.precipAccumulation,
            precipType: PrecipitationData.precipType,
            temperatureHigh: {
                _id: '',
                type: 'state',
                common: {
                    name: 'High Temperature',
                    type: 'number',
                    role: 'value.temperature.max',
                    read: true,
                    write: false,
                    unit: '°C',
                },
                native: {},
            },
            temperatureHighTime: {
                _id: '',
                type: 'state',
                common: {
                    name: 'High Temperature Time in Milliseconds',
                    type: 'number',
                    role: 'date',
                    read: true,
                    write: false,
                },
                native: {},
            },
            temperatureLow: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Low Temperature',
                    type: 'number',
                    role: 'value.temperature.min',
                    read: true,
                    write: false,
                    unit: '°C',
                },
                native: {},
            },
            temperatureLowTime: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Low Temperature Time in Milliseconds',
                    type: 'number',
                    role: 'date',
                    read: true,
                    write: false,
                },
                native: {},
            },
            apparentTemperatureHigh: {
                _id: '',
                type: 'state',
                common: {
                    name: 'High Apparent Temperature',
                    type: 'number',
                    role: 'value.temperature.max',
                    read: true,
                    write: false,
                    unit: '°C',
                },
                native: {},
            },
            apparentTemperatureHighTime: {
                _id: '',
                type: 'state',
                common: {
                    name: 'High Apparent Temperature Time in Milliseconds',
                    type: 'number',
                    role: 'date',
                    read: true,
                    write: false,
                },
                native: {},
            },
            apparentTemperatureLow: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Low Apparent Temperature',
                    type: 'number',
                    role: 'value.temperature.min',
                    read: true,
                    write: false,
                    unit: '°C',
                },
                native: {},
            },
            apparentTemperatureLowTime: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Low Apparent Temperature Time in Milliseconds',
                    type: 'number',
                    role: 'date',
                    read: true,
                    write: false,
                },
                native: {},
            },
            dewPoint: TemperatureData.dewPoint,
            humidity: TemperatureData.humidity,
            pressure: PressureVisibilityOzoneData.pressure,
            windGustTime: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Wind Gust Time in Milliseconds',
                    type: 'number',
                    role: 'date',
                    read: true,
                    write: false,
                },
                native: {},
            },
            cloudCover: CloudUvData.cloudCover,
            uvIndex: CloudUvData.uvIndex,
            uvIndexTime: {
                _id: '',
                type: 'state',
                common: {
                    name: 'UV Index Time in Milliseconds',
                    type: 'number',
                    role: 'date',
                    read: true,
                    write: false,
                    unit: '%',
                },
                native: {},
            },
            visibility: PressureVisibilityOzoneData.visibility,
            temperatureMin: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Minimum Daytime Temperature',
                    type: 'number',
                    role: 'value.temperature.min',
                    read: true,
                    write: false,
                    unit: '°C',
                },
                native: {},
            },
            temperatureMinTime: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Minimum Daytime Temperature Time in Milliseconds',
                    type: 'number',
                    role: 'date',
                    read: true,
                    write: false,
                },
                native: {},
            },
            temperatureMax: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Maximum Daytime Temperature',
                    type: 'number',
                    role: 'value.temperature.max',
                    read: true,
                    write: false,
                    unit: '°C',
                },
                native: {},
            },
            temperatureMaxTime: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Maximum Daytime Temperature Time in Milliseconds',
                    type: 'number',
                    role: 'date',
                    read: true,
                    write: false,
                },
                native: {},
            },
            apparentTemperatureMin: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Minimum Apparent Temperature',
                    type: 'number',
                    role: 'value.temperature.min',
                    read: true,
                    write: false,
                    unit: '°C',
                },
                native: {},
            },
            apparentTemperatureMinTime: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Minimum Apparent Temperature Time in Milliseconds',
                    type: 'number',
                    role: 'date',
                    read: true,
                    write: false,
                },
                native: {},
            },
            apparentTemperatureMax: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Maximum Apparent Temperature',
                    type: 'number',
                    role: 'value.temperature.max',
                    read: true,
                    write: false,
                    unit: '°C',
                },
                native: {},
            },
            apparentTemperatureMaxTime: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Maximum Apparent Temperature Time in Milliseconds',
                    type: 'number',
                    role: 'date',
                    read: true,
                    write: false,
                },
                native: {},
            },
        },
        minutely: {
            ...MetaData,
            _channel: {
                _id: '',
                type: 'folder',
                common: {
                    name: 'Minutely',
                },
                native: {},
            },
            _array: {
                _id: '',
                type: 'folder',
                common: {
                    name: 'Minutely',
                },
                native: {},
            },
            time: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Date in Milliseconds',
                    type: 'number',
                    role: 'date',
                    read: true,
                    write: false,
                },
                native: {},
            },
            precipIntensity: PrecipitationData.precipIntensity,
            precipProbability: PrecipitationData.precipProbability,
            precipIntensityError: PrecipitationData.precipIntensityError,
            precipType: PrecipitationData.precipType,
        },
        currently: {
            ...WindData,
            ...PrecipitationData,
            ...TemperatureData,
            ...PressureVisibilityOzoneData,
            ...CloudUvData,
            ...MetaData,
            _channel: {
                _id: '',
                type: 'folder',
                common: {
                    name: 'Currently',
                },
                native: {},
            },
            time: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Date in Milliseconds',
                    type: 'number',
                    role: 'date',
                    read: true,
                    write: false,
                },
                native: {},
            },
            nearestStormDistance: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Nearest Storm Distance',
                    type: 'number',
                    role: 'value.distance',
                    read: true,
                    write: false,
                    unit: 'km',
                },
                native: {},
            },
            nearestStormBearing: {
                _id: '',
                type: 'state',
                common: {
                    name: 'Nearest Storm Bearing',
                    type: 'number',
                    role: 'value',
                    read: true,
                    write: false,
                    unit: '°',
                },
                native: {},
            },
        },
        latitude: {
            _id: '',
            type: 'state',
            common: {
                name: 'Latitude',
                type: 'number',
                role: 'value.gps.latitude',
                read: true,
                write: false,
                unit: '°',
            },
            native: {},
        },
        lastUpdate: {
            _id: '',
            type: 'state',
            common: {
                name: 'Last Update',
                type: 'number',
                role: 'date',
                read: true,
                write: false,
            },
            native: {},
        },
        longitude: {
            _id: '',
            type: 'state',
            common: {
                name: 'Longitude',
                type: 'number',
                role: 'value.gps.longitude',
                read: true,
                write: false,
                unit: '°',
            },
            native: {},
        },
        timezone: {
            _id: '',
            type: 'state',
            common: {
                name: 'Timezone',
                type: 'string',
                role: 'text',
                read: true,
                write: false,
            },
            native: {},
        },
        offset: {
            _id: '',
            type: 'state',
            common: {
                name: 'Timezone Offset',
                type: 'number',
                role: 'value',
                read: true,
                write: false,
                unit: 'h',
            },
            native: {},
        },
        elevation: {
            _id: '',
            type: 'state',
            common: {
                name: 'Elevation',
                type: 'number',
                role: 'value.elevation',
                read: true,
                write: false,
                unit: 'm',
            },
            native: {},
        },
        'nearest-station': {
            _id: '',
            type: 'state',
            common: {
                name: 'Nearest Station',
                type: 'number',
                role: 'value',
                read: true,
                write: false,
            },
            native: {},
        },
        version: {
            _id: '',
            type: 'state',
            common: {
                name: 'API Version',
                type: 'string',
                role: 'text',
                read: true,
                write: false,
            },
            native: {},
        },
        units: {
            _id: '',
            type: 'state',
            common: {
                name: 'Units',
                type: 'string',
                role: 'text',
                read: true,
                write: false,
            },
            native: {},
        },
    },
};

export const Defaults = {
    state: {
        _id: 'No_definition',
        type: 'state',
        common: {
            name: 'No definition',

            type: 'string',
            role: 'text',
            read: true,
            write: false,
        },
        native: {},
    },
};

// ...existing code...

// ...existing code...

// Gemeinsame Typen für Wetterdaten
export type WindData = {
    windSpeed: number;
    windGust: number;
    windBearing: number;
    windBearingText: string;
};

export type PrecipitationData = {
    precipIntensity: number;
    precipProbability: number;
    precipIntensityError: number;
    precipAccumulation: number;
    precipType: string;
};

export type TemperatureData = {
    temperature: number;
    apparentTemperature: number;
    dewPoint: number;
    humidity: number;
};

export type PressureVisibilityOzoneData = {
    pressure: number;
    visibility: number;
    ozone: number;
};

export type CloudUvData = {
    cloudCover: number;
    uvIndex: number;
};

export type CurrentlyData = WindData &
    PrecipitationData &
    TemperatureData &
    PressureVisibilityOzoneData &
    MetaData &
    CloudUvData & {
        time: number;
        summary: string;
        icon: string;
        nearestStormDistance: number;
        nearestStormBearing: number;
    };

export type MinutelyData = {
    time: number;
    precipIntensity: number;
    precipProbability: number;
    precipIntensityError: number;
    precipType: string;
};

export type HourlyData = WindData &
    PrecipitationData &
    TemperatureData &
    PressureVisibilityOzoneData &
    CloudUvData &
    MetaData & {
        time: number;
    };

export type DailyData = WindData &
    MetaData & {
        time: number;
        sunriseTime: number;
        sunsetTime: number;
        moonPhase: number;
        precipIntensity: number;
        precipIntensityMax: number;
        precipIntensityMaxTime: number;
        precipProbability: number;
        precipAccumulation: number;
        precipType: string;
        temperatureHigh: number;
        temperatureHighTime: number;
        temperatureLow: number;
        temperatureLowTime: number;
        apparentTemperatureHigh: number;
        apparentTemperatureHighTime: number;
        apparentTemperatureLow: number;
        apparentTemperatureLowTime: number;
        dewPoint: number;
        humidity: number;
        pressure: number;
        windGustTime: number;
        cloudCover: number;
        uvIndex: number;
        uvIndexTime: number;
        visibility: number;
        temperatureMin: number;
        temperatureMinTime: number;
        temperatureMax: number;
        temperatureMaxTime: number;
        apparentTemperatureMin: number;
        apparentTemperatureMinTime: number;
        apparentTemperatureMax: number;
        apparentTemperatureMaxTime: number;
    };
type MetaData = {
    summary: string;
    icon: string;
};
// Haupttyp
export type PirateWeatherTestdata = {
    lastUpdate?: number;
    latitude: number;
    longitude: number;
    timezone: string;
    offset: number;
    elevation: number;
    units?: string;
    'nearest-station'?: number;
    version?: string;
    currently: CurrentlyData;
    minutely?: MetaData & {
        data: MinutelyData[];
    };
    hourly: MetaData & {
        data: HourlyData[];
    };
    daily: MetaData & {
        data: DailyData[];
    };
    flags?: {
        sources: string[];
        sourceTimes: { [key: string]: string };
        'nearest-station': number;
        units: string;
        version: string;
    };
};

export function setUnits(u: 'si' | 'us' | 'ca' | 'uk'): void {
    switch (u) {
        default:
        case 'si': {
            break;
        }
        case 'us': {
            TemperatureData.apparentTemperature.common.unit = '°F';
            TemperatureData.dewPoint.common.unit = '°F';
            TemperatureData.temperature.common.unit = '°F';
            WindData.windSpeed.common.unit = 'mph';
            WindData.windGust.common.unit = 'mph';
            PressureVisibilityOzoneData.pressure.common.unit = 'mbar';
            PressureVisibilityOzoneData.visibility.common.unit = 'mi';
            PrecipitationData.precipIntensity.common.unit = 'in';
            PrecipitationData.precipIntensityError.common.unit = 'in';
            PrecipitationData.precipAccumulation.common.unit = 'in';
            genericStateObjects.weather.daily.temperatureHigh.common.unit = '°F';
            genericStateObjects.weather.daily.temperatureLow.common.unit = '°F';
            genericStateObjects.weather.daily.apparentTemperatureHigh.common.unit = '°F';
            genericStateObjects.weather.daily.apparentTemperatureLow.common.unit = '°F';
            genericStateObjects.weather.daily.temperatureMin.common.unit = '°F';
            genericStateObjects.weather.daily.temperatureMax.common.unit = '°F';
            genericStateObjects.weather.daily.apparentTemperatureMin.common.unit = '°F';
            genericStateObjects.weather.daily.apparentTemperatureMax.common.unit = '°F';
            genericStateObjects.weather.daily.precipIntensity.common.unit = 'in';
            genericStateObjects.weather.daily.precipAccumulation.common.unit = 'in';
            genericStateObjects.weather.daily.precipIntensityMax.common.unit = 'in';
            genericStateObjects.weather.currently.nearestStormDistance.common.unit = 'mi';
            genericStateObjects.weather.elevation.common.unit = 'ft';

            break;
        }
        case 'ca': {
            WindData.windSpeed.common.unit = 'km/h';
            WindData.windGust.common.unit = 'km/h';
            break;
        }
        case 'uk': {
            WindData.windSpeed.common.unit = 'mph';
            WindData.windGust.common.unit = 'mph';
            genericStateObjects.weather.currently.nearestStormDistance.common.unit = 'mi';
            break;
        }
    }
}
// ...existing code...

// ...existing code...

export const testdata = {
    latitude: 49.8074,
    longitude: 7.4556,
    timezone: 'Europe/Berlin',
    offset: 2,
    elevation: 318,
    currently: {
        time: 1754747100,
        summary: 'Clear',
        icon: 'clear-day',
        nearestStormDistance: 74.69,
        nearestStormBearing: 28,
        precipIntensity: 0,
        precipProbability: 0,
        precipIntensityError: 0,
        precipType: 'none',
        temperature: 30.5,
        apparentTemperature: 28.84,
        dewPoint: 12.35,
        humidity: 0.32,
        pressure: 1018.31,
        windSpeed: 3.32,
        windGust: 5.72,
        windBearing: 225,
        cloudCover: 0.04,
        uvIndex: 5.58,
        visibility: 16.09,
        ozone: 296.36,
    },
    minutely: {
        summary: 'Clear for the hour.',
        icon: 'clear-day',
        data: [
            { time: 1754747100, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754747160, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754747220, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754747280, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754747340, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754747400, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754747460, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754747520, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754747580, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754747640, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754747700, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754747760, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754747820, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754747880, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754747940, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754748000, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754748060, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754748120, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754748180, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754748240, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754748300, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754748360, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754748420, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754748480, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754748540, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754748600, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754748660, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754748720, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754748780, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754748840, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754748900, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754748960, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754749020, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754749080, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754749140, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754749200, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754749260, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754749320, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754749380, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754749440, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754749500, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754749560, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754749620, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754749680, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754749740, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754749800, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754749860, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754749920, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754749980, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754750040, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754750100, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754750160, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754750220, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754750280, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754750340, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754750400, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754750460, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754750520, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754750580, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754750640, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
            { time: 1754750700, precipIntensity: 0, precipProbability: 0, precipIntensityError: 0, precipType: 'none' },
        ],
    },
    hourly: {
        summary: 'Clear throughout the day.',
        icon: 'clear-day',
        data: [
            {
                time: 1754744400,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 30.15,
                apparentTemperature: 28.74,
                dewPoint: 12.24,
                humidity: 0.33,
                pressure: 1018.5,
                windSpeed: 2.95,
                windGust: 5.11,
                windBearing: 202,
                cloudCover: 0.04,
                uvIndex: 6.09,
                visibility: 16.09,
                ozone: 296.14,
            },
            {
                time: 1754748000,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 30.62,
                apparentTemperature: 28.83,
                dewPoint: 12.39,
                humidity: 0.32,
                pressure: 1018.24,
                windSpeed: 3.52,
                windGust: 5.93,
                windBearing: 224,
                cloudCover: 0.03,
                uvIndex: 5.4,
                visibility: 16.09,
                ozone: 296.43,
            },
            {
                time: 1754751600,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 30.48,
                apparentTemperature: 28.34,
                dewPoint: 12.39,
                humidity: 0.32,
                pressure: 1018.08,
                windSpeed: 4,
                windGust: 6.02,
                windBearing: 237,
                cloudCover: 0,
                uvIndex: 4.34,
                visibility: 16.09,
                ozone: 295.6,
            },
            {
                time: 1754755200,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 30.01,
                apparentTemperature: 28.04,
                dewPoint: 12.43,
                humidity: 0.34,
                pressure: 1018.24,
                windSpeed: 3.81,
                windGust: 6.01,
                windBearing: 254,
                cloudCover: 0,
                uvIndex: 3.07,
                visibility: 16.09,
                ozone: 294.63,
            },
            {
                time: 1754758800,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 28.65,
                apparentTemperature: 27.66,
                dewPoint: 14.13,
                humidity: 0.41,
                pressure: 1018.56,
                windSpeed: 3.2,
                windGust: 5.9,
                windBearing: 285,
                cloudCover: 0,
                uvIndex: 1.8,
                visibility: 16.09,
                ozone: 293.84,
            },
            {
                time: 1754762400,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 25.09,
                apparentTemperature: 25.05,
                dewPoint: 15.23,
                humidity: 0.55,
                pressure: 1019.03,
                windSpeed: 2.51,
                windGust: 4.91,
                windBearing: 306,
                cloudCover: 0,
                uvIndex: 0.78,
                visibility: 16.09,
                ozone: 293.21,
            },
            {
                time: 1754766000,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 21.98,
                apparentTemperature: 21.91,
                dewPoint: 14.92,
                humidity: 0.64,
                pressure: 1019.81,
                windSpeed: 2.4,
                windGust: 3.9,
                windBearing: 303,
                cloudCover: 0,
                uvIndex: 0.14,
                visibility: 16.09,
                ozone: 291.8,
            },
            {
                time: 1754769600,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 20.58,
                apparentTemperature: 20.71,
                dewPoint: 14.85,
                humidity: 0.69,
                pressure: 1020.58,
                windSpeed: 2.01,
                windGust: 2.31,
                windBearing: 307,
                cloudCover: 0,
                uvIndex: 0,
                visibility: 16.09,
                ozone: 291.25,
            },
            {
                time: 1754773200,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 19.44,
                apparentTemperature: 19.53,
                dewPoint: 14.73,
                humidity: 0.74,
                pressure: 1021.07,
                windSpeed: 2,
                windGust: 2.1,
                windBearing: 337,
                cloudCover: 0,
                uvIndex: 0,
                visibility: 16.09,
                ozone: 290.31,
            },
            {
                time: 1754776800,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 18.72,
                apparentTemperature: 18.33,
                dewPoint: 13.54,
                humidity: 0.72,
                pressure: 1021.65,
                windSpeed: 2.14,
                windGust: 3.04,
                windBearing: 334,
                cloudCover: 0.01,
                uvIndex: 0,
                visibility: 16.09,
                ozone: 290,
            },
            {
                time: 1754780400,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 17.91,
                apparentTemperature: 16.66,
                dewPoint: 11.9,
                humidity: 0.68,
                pressure: 1022.16,
                windSpeed: 2.61,
                windGust: 3.02,
                windBearing: 337,
                cloudCover: 0.03,
                uvIndex: 0,
                visibility: 16.09,
                ozone: 291.46,
            },
            {
                time: 1754784000,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 16.7,
                apparentTemperature: 15.05,
                dewPoint: 10.43,
                humidity: 0.66,
                pressure: 1022.5,
                windSpeed: 2.57,
                windGust: 2.8,
                windBearing: 329,
                cloudCover: 0.02,
                uvIndex: 0,
                visibility: 16.09,
                ozone: 291.19,
            },
            {
                time: 1754787600,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 15.61,
                apparentTemperature: 13.79,
                dewPoint: 9.33,
                humidity: 0.66,
                pressure: 1022.66,
                windSpeed: 2.4,
                windGust: 2.23,
                windBearing: 325,
                cloudCover: 0.04,
                uvIndex: 0,
                visibility: 16.09,
                ozone: 291.73,
            },
            {
                time: 1754791200,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 14.83,
                apparentTemperature: 12.87,
                dewPoint: 8.8,
                humidity: 0.67,
                pressure: 1022.91,
                windSpeed: 2.42,
                windGust: 2.33,
                windBearing: 331,
                cloudCover: 0.12,
                uvIndex: 0,
                visibility: 16.09,
                ozone: 292.07,
            },
            {
                time: 1754794800,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 14.2,
                apparentTemperature: 12.32,
                dewPoint: 8.7,
                humidity: 0.69,
                pressure: 1023.19,
                windSpeed: 2.26,
                windGust: 2.02,
                windBearing: 331,
                cloudCover: 0.05,
                uvIndex: 0,
                visibility: 16.09,
                ozone: 291.9,
            },
            {
                time: 1754798400,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 13.69,
                apparentTemperature: 11.87,
                dewPoint: 8.71,
                humidity: 0.72,
                pressure: 1023.47,
                windSpeed: 2.19,
                windGust: 2.02,
                windBearing: 332,
                cloudCover: 0.12,
                uvIndex: 0,
                visibility: 16.09,
                ozone: 292.9,
            },
            {
                time: 1754802000,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 13.94,
                apparentTemperature: 12.01,
                dewPoint: 9.03,
                humidity: 0.72,
                pressure: 1024.19,
                windSpeed: 2.44,
                windGust: 3,
                windBearing: 334,
                cloudCover: 0.05,
                uvIndex: 0.08,
                visibility: 16.09,
                ozone: 294.07,
            },
            {
                time: 1754805600,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 16.25,
                apparentTemperature: 14.67,
                dewPoint: 9.62,
                humidity: 0.65,
                pressure: 1024.51,
                windSpeed: 2.19,
                windGust: 3.63,
                windBearing: 344,
                cloudCover: 0.04,
                uvIndex: 0.63,
                visibility: 16.09,
                ozone: 295.73,
            },
            {
                time: 1754809200,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 18.56,
                apparentTemperature: 16.77,
                dewPoint: 8.93,
                humidity: 0.54,
                pressure: 1024.67,
                windSpeed: 2.22,
                windGust: 4.01,
                windBearing: 355,
                cloudCover: 0,
                uvIndex: 1.58,
                visibility: 16.09,
                ozone: 296.58,
            },
            {
                time: 1754812800,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 20.57,
                apparentTemperature: 18.33,
                dewPoint: 8.01,
                humidity: 0.44,
                pressure: 1024.7,
                windSpeed: 2.52,
                windGust: 3.6,
                windBearing: 8,
                cloudCover: 0,
                uvIndex: 2.82,
                visibility: 16.09,
                ozone: 296.42,
            },
            {
                time: 1754816400,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 22.47,
                apparentTemperature: 19.74,
                dewPoint: 7.45,
                humidity: 0.38,
                pressure: 1024.88,
                windSpeed: 3.02,
                windGust: 3.52,
                windBearing: 15,
                cloudCover: 0,
                uvIndex: 4.11,
                visibility: 16.09,
                ozone: 295.84,
            },
            {
                time: 1754820000,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 23.95,
                apparentTemperature: 21.05,
                dewPoint: 6.85,
                humidity: 0.33,
                pressure: 1024.86,
                windSpeed: 3.07,
                windGust: 3.22,
                windBearing: 19,
                cloudCover: 0,
                uvIndex: 5.23,
                visibility: 16.09,
                ozone: 296.04,
            },
            {
                time: 1754823600,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 25.1,
                apparentTemperature: 22.03,
                dewPoint: 5.95,
                humidity: 0.29,
                pressure: 1024.73,
                windSpeed: 3.03,
                windGust: 2.92,
                windBearing: 21,
                cloudCover: 0,
                uvIndex: 5.99,
                visibility: 16.09,
                ozone: 296.84,
            },
            {
                time: 1754827200,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 26.02,
                apparentTemperature: 22.95,
                dewPoint: 5.29,
                humidity: 0.26,
                pressure: 1024.45,
                windSpeed: 2.84,
                windGust: 2.7,
                windBearing: 23,
                cloudCover: 0,
                uvIndex: 6.29,
                visibility: 16.09,
                ozone: 296.88,
            },
            {
                time: 1754830800,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 26.59,
                apparentTemperature: 23.6,
                dewPoint: 5.02,
                humidity: 0.25,
                pressure: 1024.14,
                windSpeed: 2.64,
                windGust: 2.71,
                windBearing: 24,
                cloudCover: 0,
                uvIndex: 6.07,
                visibility: 16.09,
                ozone: 296.28,
            },
            {
                time: 1754834400,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 26.98,
                apparentTemperature: 24.05,
                dewPoint: 5.25,
                humidity: 0.25,
                pressure: 1023.74,
                windSpeed: 2.63,
                windGust: 2.62,
                windBearing: 25,
                cloudCover: 0.02,
                uvIndex: 5.39,
                visibility: 16.09,
                ozone: 295.58,
            },
            {
                time: 1754838000,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 26.91,
                apparentTemperature: 24.04,
                dewPoint: 6,
                humidity: 0.26,
                pressure: 1023.5,
                windSpeed: 2.72,
                windGust: 2.7,
                windBearing: 22,
                cloudCover: 0,
                uvIndex: 4.32,
                visibility: 16.09,
                ozone: 294.7,
            },
            {
                time: 1754841600,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 26.49,
                apparentTemperature: 23.6,
                dewPoint: 6.77,
                humidity: 0.29,
                pressure: 1023.43,
                windSpeed: 3.06,
                windGust: 3.02,
                windBearing: 18,
                cloudCover: 0,
                uvIndex: 3.04,
                visibility: 16.09,
                ozone: 293.88,
            },
            {
                time: 1754845200,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 25.11,
                apparentTemperature: 22.67,
                dewPoint: 9.03,
                humidity: 0.36,
                pressure: 1023.26,
                windSpeed: 3.11,
                windGust: 5,
                windBearing: 12,
                cloudCover: 0,
                uvIndex: 1.78,
                visibility: 16.09,
                ozone: 292.77,
            },
            {
                time: 1754848800,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 21.41,
                apparentTemperature: 19.57,
                dewPoint: 10,
                humidity: 0.48,
                pressure: 1023.6,
                windSpeed: 2.61,
                windGust: 3.7,
                windBearing: 354,
                cloudCover: 0,
                uvIndex: 0.76,
                visibility: 16.09,
                ozone: 291.22,
            },
            {
                time: 1754852400,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 18.27,
                apparentTemperature: 16.22,
                dewPoint: 8.51,
                humidity: 0.53,
                pressure: 1024.11,
                windSpeed: 2.44,
                windGust: 2.52,
                windBearing: 358,
                cloudCover: 0,
                uvIndex: 0.13,
                visibility: 16.09,
                ozone: 290.01,
            },
            {
                time: 1754856000,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 16.77,
                apparentTemperature: 14.94,
                dewPoint: 8.05,
                humidity: 0.56,
                pressure: 1024.66,
                windSpeed: 1.94,
                windGust: 1.91,
                windBearing: 358,
                cloudCover: 0,
                uvIndex: 0,
                visibility: 16.09,
                ozone: 289.84,
            },
            {
                time: 1754859600,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 16.03,
                apparentTemperature: 14.17,
                dewPoint: 7.96,
                humidity: 0.59,
                pressure: 1024.54,
                windSpeed: 1.98,
                windGust: 1.9,
                windBearing: 8,
                cloudCover: 0,
                uvIndex: 0,
                visibility: 16.09,
                ozone: 289.67,
            },
            {
                time: 1754863200,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 15.23,
                apparentTemperature: 13.59,
                dewPoint: 8.03,
                humidity: 0.62,
                pressure: 1024.44,
                windSpeed: 1.69,
                windGust: 1.71,
                windBearing: 17,
                cloudCover: 0,
                uvIndex: 0,
                visibility: 16.09,
                ozone: 289.46,
            },
            {
                time: 1754866800,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 14.88,
                apparentTemperature: 13.01,
                dewPoint: 7.79,
                humidity: 0.62,
                pressure: 1024.45,
                windSpeed: 1.91,
                windGust: 1.8,
                windBearing: 24,
                cloudCover: 0,
                uvIndex: 0,
                visibility: 16.09,
                ozone: 290,
            },
            {
                time: 1754870400,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 14.4,
                apparentTemperature: 12.47,
                dewPoint: 7.49,
                humidity: 0.63,
                pressure: 1024.2,
                windSpeed: 1.93,
                windGust: 1.9,
                windBearing: 32,
                cloudCover: 0.02,
                uvIndex: 0,
                visibility: 16.09,
                ozone: 289.9,
            },
            {
                time: 1754874000,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 13.86,
                apparentTemperature: 11.76,
                dewPoint: 7.28,
                humidity: 0.64,
                pressure: 1023.68,
                windSpeed: 2.08,
                windGust: 2.02,
                windBearing: 29,
                cloudCover: 0,
                uvIndex: 0,
                visibility: 16.09,
                ozone: 289.4,
            },
            {
                time: 1754877600,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 13.36,
                apparentTemperature: 11.18,
                dewPoint: 7.3,
                humidity: 0.66,
                pressure: 1023.51,
                windSpeed: 2.19,
                windGust: 2.12,
                windBearing: 28,
                cloudCover: 0.05,
                uvIndex: 0,
                visibility: 16.09,
                ozone: 287.75,
            },
            {
                time: 1754881200,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 12.96,
                apparentTemperature: 10.78,
                dewPoint: 7.41,
                humidity: 0.69,
                pressure: 1023.16,
                windSpeed: 2.23,
                windGust: 2.21,
                windBearing: 30,
                cloudCover: 0.01,
                uvIndex: 0,
                visibility: 16.09,
                ozone: 286.95,
            },
            {
                time: 1754884800,
                summary: 'Clear',
                icon: 'clear-night',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 12.47,
                apparentTemperature: 10.38,
                dewPoint: 7.46,
                humidity: 0.71,
                pressure: 1022.85,
                windSpeed: 2.11,
                windGust: 2.1,
                windBearing: 30,
                cloudCover: 0,
                uvIndex: 0,
                visibility: 16.09,
                ozone: 286.24,
            },
            {
                time: 1754888400,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 13.05,
                apparentTemperature: 11.06,
                dewPoint: 7.91,
                humidity: 0.71,
                pressure: 1022.96,
                windSpeed: 2.12,
                windGust: 2.11,
                windBearing: 32,
                cloudCover: 0,
                uvIndex: 0.08,
                visibility: 16.09,
                ozone: 285.75,
            },
            {
                time: 1754892000,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 15.72,
                apparentTemperature: 13.88,
                dewPoint: 8.67,
                humidity: 0.63,
                pressure: 1022.61,
                windSpeed: 2.2,
                windGust: 7.71,
                windBearing: 44,
                cloudCover: 0,
                uvIndex: 0.62,
                visibility: 16.09,
                ozone: 285.53,
            },
            {
                time: 1754895600,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 18.24,
                apparentTemperature: 15.45,
                dewPoint: 8.57,
                humidity: 0.53,
                pressure: 1022.05,
                windSpeed: 3.48,
                windGust: 6.62,
                windBearing: 64,
                cloudCover: 0,
                uvIndex: 1.58,
                visibility: 16.09,
                ozone: 285.17,
            },
            {
                time: 1754899200,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 20.34,
                apparentTemperature: 17.2,
                dewPoint: 8.58,
                humidity: 0.46,
                pressure: 1021.6,
                windSpeed: 3.99,
                windGust: 6.22,
                windBearing: 70,
                cloudCover: 0,
                uvIndex: 2.82,
                visibility: 16.09,
                ozone: 284.1,
            },
            {
                time: 1754902800,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 22.48,
                apparentTemperature: 18.98,
                dewPoint: 8.68,
                humidity: 0.41,
                pressure: 1021.17,
                windSpeed: 4.51,
                windGust: 6.01,
                windBearing: 73,
                cloudCover: 0,
                uvIndex: 4.12,
                visibility: 16.09,
                ozone: 284.83,
            },
            {
                time: 1754906400,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 24.16,
                apparentTemperature: 20.61,
                dewPoint: 8.68,
                humidity: 0.37,
                pressure: 1020.78,
                windSpeed: 4.63,
                windGust: 5.41,
                windBearing: 76,
                cloudCover: 0,
                uvIndex: 5.24,
                visibility: 16.09,
                ozone: 286,
            },
            {
                time: 1754910000,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 25.41,
                apparentTemperature: 22.08,
                dewPoint: 8.85,
                humidity: 0.35,
                pressure: 1020.09,
                windSpeed: 4.37,
                windGust: 4.61,
                windBearing: 78,
                cloudCover: 0,
                uvIndex: 6,
                visibility: 16.09,
                ozone: 286.58,
            },
            {
                time: 1754913600,
                summary: 'Clear',
                icon: 'clear-day',
                precipIntensity: 0,
                precipProbability: 0,
                precipIntensityError: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperature: 26.58,
                apparentTemperature: 23.72,
                dewPoint: 9.35,
                humidity: 0.34,
                pressure: 1019.39,
                windSpeed: 3.9,
                windGust: 4.1,
                windBearing: 82,
                cloudCover: 0,
                uvIndex: 6.29,
                visibility: 16.09,
                ozone: 287.55,
            },
        ],
    },
    daily: {
        summary: 'Light rain on Thursday and Friday, with high temperatures peaking at 34°C on Thursday.',
        icon: 'light-rain',
        data: [
            {
                time: 1754690400,
                summary: 'Clear starting in the evening.',
                icon: 'clear-day',
                sunriseTime: 1754712726,
                sunsetTime: 1754765895,
                moonPhase: 0.5,
                precipIntensity: 0,
                precipIntensityMax: 0,
                precipIntensityMaxTime: 1754690400,
                precipProbability: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperatureHigh: 30.62,
                temperatureHighTime: 1754748000,
                temperatureLow: 13.69,
                temperatureLowTime: 1754798400,
                apparentTemperatureHigh: 28.83,
                apparentTemperatureHighTime: 1754748000,
                apparentTemperatureLow: 11.87,
                apparentTemperatureLowTime: 1754798400,
                dewPoint: 13.71,
                humidity: 0.63,
                pressure: 1019.75,
                windSpeed: 1.77,
                windGust: 2.54,
                windGustTime: 1754751600,
                windBearing: 261,
                cloudCover: 0.55,
                uvIndex: 6.29,
                uvIndexTime: 1754740800,
                visibility: 16.09,
                temperatureMin: 15.76,
                temperatureMinTime: 1754708400,
                temperatureMax: 30.62,
                temperatureMaxTime: 1754748000,
                apparentTemperatureMin: 16.14,
                apparentTemperatureMinTime: 1754704800,
                apparentTemperatureMax: 28.83,
                apparentTemperatureMaxTime: 1754748000,
            },
            {
                time: 1754776800,
                summary: 'Clear throughout the day.',
                icon: 'clear-day',
                sunriseTime: 1754799213,
                sunsetTime: 1754852190,
                moonPhase: 0.54,
                precipIntensity: 0,
                precipIntensityMax: 0,
                precipIntensityMaxTime: 1754776800,
                precipProbability: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperatureHigh: 26.98,
                temperatureHighTime: 1754834400,
                temperatureLow: 12.47,
                temperatureLowTime: 1754884800,
                apparentTemperatureHigh: 24.05,
                apparentTemperatureHighTime: 1754834400,
                apparentTemperatureLow: 10.38,
                apparentTemperatureLowTime: 1754884800,
                dewPoint: 8.3,
                humidity: 0.5,
                pressure: 1023.77,
                windSpeed: 2.54,
                windGust: 2.92,
                windGustTime: 1754845200,
                windBearing: 192,
                cloudCover: 0.02,
                uvIndex: 6.29,
                uvIndexTime: 1754827200,
                visibility: 16.09,
                temperatureMin: 13.69,
                temperatureMinTime: 1754798400,
                temperatureMax: 26.98,
                temperatureMaxTime: 1754834400,
                apparentTemperatureMin: 11.87,
                apparentTemperatureMinTime: 1754798400,
                apparentTemperatureMax: 24.05,
                apparentTemperatureMaxTime: 1754834400,
            },
            {
                time: 1754863200,
                summary: 'Clear throughout the day.',
                icon: 'clear-day',
                sunriseTime: 1754885700,
                sunsetTime: 1754938483,
                moonPhase: 0.58,
                precipIntensity: 0,
                precipIntensityMax: 0,
                precipIntensityMaxTime: 1754863200,
                precipProbability: 0,
                precipAccumulation: 0,
                precipType: 'none',
                temperatureHigh: 27.85,
                temperatureHighTime: 1754924400,
                temperatureLow: 15.66,
                temperatureLowTime: 1754971200,
                apparentTemperatureHigh: 25.96,
                apparentTemperatureHighTime: 1754924400,
                apparentTemperatureLow: 14.18,
                apparentTemperatureLowTime: 1754971200,
                dewPoint: 9.09,
                humidity: 0.51,
                pressure: 1020.57,
                windSpeed: 2.68,
                windGust: 3.27,
                windGustTime: 1754892000,
                windBearing: 50,
                cloudCover: 0.01,
                uvIndex: 6.29,
                uvIndexTime: 1754913600,
                visibility: 16.09,
                temperatureMin: 12.47,
                temperatureMinTime: 1754884800,
                temperatureMax: 27.85,
                temperatureMaxTime: 1754924400,
                apparentTemperatureMin: 10.38,
                apparentTemperatureMinTime: 1754884800,
                apparentTemperatureMax: 25.96,
                apparentTemperatureMaxTime: 1754924400,
            },
            {
                time: 1754949600,
                summary: 'Mostly clear in the morning and evening.',
                icon: 'mostly-clear-day',
                sunriseTime: 1754972188,
                sunsetTime: 1755024775,
                moonPhase: 0.61,
                precipIntensity: 0,
                precipIntensityMax: 0,
                precipIntensityMaxTime: 1754949600,
                precipProbability: 0,
                precipAccumulation: 0,
                precipType: 'rain',
                temperatureHigh: 31.39,
                temperatureHighTime: 1755010800,
                temperatureLow: 19.06,
                temperatureLowTime: 1755054000,
                apparentTemperatureHigh: 30.63,
                apparentTemperatureHighTime: 1755010800,
                apparentTemperatureLow: 19.87,
                apparentTemperatureLowTime: 1755054000,
                dewPoint: 11.32,
                humidity: 0.49,
                pressure: 1014.88,
                windSpeed: 1.79,
                windGust: 2.03,
                windGustTime: 1755021600,
                windBearing: 72,
                cloudCover: 0.37,
                uvIndex: 5.63,
                uvIndexTime: 1755000000,
                visibility: 16.09,
                temperatureMin: 15.66,
                temperatureMinTime: 1754971200,
                temperatureMax: 31.39,
                temperatureMaxTime: 1755010800,
                apparentTemperatureMin: 14.18,
                apparentTemperatureMinTime: 1754971200,
                apparentTemperatureMax: 30.63,
                apparentTemperatureMaxTime: 1755010800,
            },
            {
                time: 1755036000,
                summary: 'Possible drizzle overnight.',
                icon: 'possible-rain-day',
                sunriseTime: 1755058675,
                sunsetTime: 1755111065,
                moonPhase: 0.65,
                precipIntensity: 0.004,
                precipIntensityMax: 0.057,
                precipIntensityMaxTime: 1755118800,
                precipProbability: 0.1,
                precipAccumulation: 0.0096,
                precipType: 'rain',
                temperatureHigh: 33.63,
                temperatureHighTime: 1755097200,
                temperatureLow: 18.48,
                temperatureLowTime: 1755140400,
                apparentTemperatureHigh: 32.29,
                apparentTemperatureHighTime: 1755097200,
                apparentTemperatureLow: 19.13,
                apparentTemperatureLowTime: 1755140400,
                dewPoint: 13.3,
                humidity: 0.49,
                pressure: 1013.16,
                windSpeed: 1.69,
                windGust: 2.35,
                windGustTime: 1755075600,
                windBearing: 198,
                cloudCover: 0.98,
                uvIndex: 4.77,
                uvIndexTime: 1755086400,
                visibility: 16.09,
                temperatureMin: 19.06,
                temperatureMinTime: 1755054000,
                temperatureMax: 33.63,
                temperatureMaxTime: 1755097200,
                apparentTemperatureMin: 19.87,
                apparentTemperatureMinTime: 1755054000,
                apparentTemperatureMax: 32.29,
                apparentTemperatureMaxTime: 1755097200,
            },
            {
                time: 1755122400,
                summary: 'Drizzle until afternoon, starting again overnight.',
                icon: 'drizzle',
                sunriseTime: 1755145163,
                sunsetTime: 1755197355,
                moonPhase: 0.68,
                precipIntensity: 0.0463,
                precipIntensityMax: 0.155,
                precipIntensityMaxTime: 1755205200,
                precipProbability: 0.3,
                precipAccumulation: 0.1111,
                precipType: 'rain',
                temperatureHigh: 34.31,
                temperatureHighTime: 1755183600,
                temperatureLow: 20.3,
                temperatureLowTime: 1755226800,
                apparentTemperatureHigh: 32.72,
                apparentTemperatureHighTime: 1755183600,
                apparentTemperatureLow: 21.3,
                apparentTemperatureLowTime: 1755226800,
                dewPoint: 14.02,
                humidity: 0.51,
                pressure: 1012.68,
                windSpeed: 1.72,
                windGust: 2.44,
                windGustTime: 1755183600,
                windBearing: 204,
                cloudCover: 0.74,
                uvIndex: 5.49,
                uvIndexTime: 1755172800,
                visibility: 16.09,
                temperatureMin: 18.48,
                temperatureMinTime: 1755140400,
                temperatureMax: 34.31,
                temperatureMaxTime: 1755183600,
                apparentTemperatureMin: 19.13,
                apparentTemperatureMinTime: 1755140400,
                apparentTemperatureMax: 32.72,
                apparentTemperatureMaxTime: 1755183600,
            },
            {
                time: 1755208800,
                summary: 'Possible light rain until afternoon, starting again overnight.',
                icon: 'possible-rain-day',
                sunriseTime: 1755231651,
                sunsetTime: 1755283643,
                moonPhase: 0.72,
                precipIntensity: 0.0823,
                precipIntensityMax: 0.413,
                precipIntensityMaxTime: 1755291600,
                precipProbability: 0.28,
                precipAccumulation: 0.1975,
                precipType: 'rain',
                temperatureHigh: 33.49,
                temperatureHighTime: 1755270000,
                temperatureLow: 18.88,
                temperatureLowTime: 1755313200,
                apparentTemperatureHigh: 32.97,
                apparentTemperatureHighTime: 1755270000,
                apparentTemperatureLow: 20.45,
                apparentTemperatureLowTime: 1755313200,
                dewPoint: 15.4,
                humidity: 0.56,
                pressure: 1012.39,
                windSpeed: 1.6,
                windGust: 2.28,
                windGustTime: 1755259200,
                windBearing: 159,
                cloudCover: 0.46,
                uvIndex: 5.37,
                uvIndexTime: 1755259200,
                visibility: 15.61,
                temperatureMin: 20.3,
                temperatureMinTime: 1755226800,
                temperatureMax: 33.49,
                temperatureMaxTime: 1755270000,
                apparentTemperatureMin: 21.3,
                apparentTemperatureMinTime: 1755226800,
                apparentTemperatureMax: 32.97,
                apparentTemperatureMaxTime: 1755270000,
            },
            {
                time: 1755295200,
                summary: 'Possible drizzle throughout the day.',
                icon: 'possible-rain-day',
                sunriseTime: 1755318140,
                sunsetTime: 1755369930,
                moonPhase: 0.76,
                precipIntensity: 0.1007,
                precipIntensityMax: 0.342,
                precipIntensityMaxTime: 1755295200,
                precipProbability: 0.23,
                precipAccumulation: 0.2417,
                precipType: 'rain',
                temperatureHigh: 30.37,
                temperatureHighTime: 1755356400,
                temperatureLow: 16.93,
                temperatureLowTime: 1755396000,
                apparentTemperatureHigh: 29.02,
                apparentTemperatureHighTime: 1755356400,
                apparentTemperatureLow: 17.26,
                apparentTemperatureLowTime: 1755396000,
                dewPoint: 16.38,
                humidity: 0.67,
                pressure: 1013.6,
                windSpeed: 2.02,
                windGust: 3.13,
                windGustTime: 1755345600,
                windBearing: 229,
                cloudCover: 0.57,
                uvIndex: 4.8,
                uvIndexTime: 1755345600,
                visibility: 16.09,
                temperatureMin: 18.57,
                temperatureMinTime: 1755378000,
                temperatureMax: 30.37,
                temperatureMaxTime: 1755356400,
                apparentTemperatureMin: 19.43,
                apparentTemperatureMinTime: 1755378000,
                apparentTemperatureMax: 29.02,
                apparentTemperatureMaxTime: 1755356400,
            },
        ],
    },
    flags: {
        sources: ['ETOPO1', 'gfs', 'gefs'],
        sourceTimes: { gfs: '2025-08-07 12Z', gefs: '2025-08-09 06Z' },
        'nearest-station': 0,
        units: 'si',
        version: 'V2.7.5',
    },
};
